<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Throwable;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();

        foreach (self::countries() as $country) {
            try {
                $Country = new Country($country);
                $Country->saveOrFail();
            }
            catch(Throwable $e) {
                echo 'Error during country seeding ' . json_encode($country) . ', skipping' . PHP_EOL;
            }
        }
    }

    /**
     * Countries data provider
     *
     * @return array
     */
    public static function countries(): array
    {
        return [
            ["isoCode" => "AB", "name" => "Abkhazia"],
            ["isoCode" => "AU", "name" => "Australia"],
            ["isoCode" => "AT", "name" => "Austria"],
            ["isoCode" => "AZ", "name" => "Azerbaijan"],
            ["isoCode" => "AL", "name" => "Albania"],
            ["isoCode" => "DZ", "name" => "Algeria"],
            ["isoCode" => "AS", "name" => "American Samoa"],
            ["isoCode" => "AI", "name" => "Anguilla"],
            ["isoCode" => "AO", "name" => "Angola"],
            ["isoCode" => "AD", "name" => "Andorra"],
            ["isoCode" => "AQ", "name" => "Antarctica"],
            ["isoCode" => "AG", "name" => "Antigua and Barbuda"],
            ["isoCode" => "AR", "name" => "Argentina"],
            ["isoCode" => "AM", "name" => "Armenia"],
            ["isoCode" => "AW", "name" => "Aruba"],
            ["isoCode" => "AF", "name" => "Afghanistan"],
            ["isoCode" => "BS", "name" => "Bahamas"],
            ["isoCode" => "BD", "name" => "Bangladesh"],
            ["isoCode" => "BB", "name" => "Barbados"],
            ["isoCode" => "BH", "name" => "Bahrain"],
            ["isoCode" => "BY", "name" => "Belarus"],
            ["isoCode" => "BZ", "name" => "Belize"],
            ["isoCode" => "BE", "name" => "Belgium"],
            ["isoCode" => "BJ", "name" => "Benin"],
            ["isoCode" => "BM", "name" => "Bermuda"],
            ["isoCode" => "BG", "name" => "Bulgaria"],
            ["isoCode" => "BO", "name" => "Bolivia"],
            ["isoCode" => "BQ", "name" => "Bonaire, Sint Eustatius and Saba"],
            ["isoCode" => "BA", "name" => "Bosnia and Herzegovina"],
            ["isoCode" => "BW", "name" => "Botswana"],
            ["isoCode" => "BR", "name" => "Brazil"],
            ["isoCode" => "IO", "name" => "British Indian Ocean Territory"],
            ["isoCode" => "BN", "name" => "Brunei Darussalam"],
            ["isoCode" => "BF", "name" => "Burkina Faso"],
            ["isoCode" => "BI", "name" => "Burundi"],
            ["isoCode" => "BT", "name" => "Bhutan"],
            ["isoCode" => "VU", "name" => "Vanuatu"],
            ["isoCode" => "HU", "name" => "Hungary"],
            ["isoCode" => "VE", "name" => "Venezuela"],
            ["isoCode" => "VG", "name" => "Virgin Islands, British"],
            ["isoCode" => "VI", "name" => "Virgin Islands, U.S."],
            ["isoCode" => "VN", "name" => "Vietnam"],
            ["isoCode" => "GA", "name" => "Gabon"],
            ["isoCode" => "HT", "name" => "Haiti"],
            ["isoCode" => "GY", "name" => "Guyana"],
            ["isoCode" => "GM", "name" => "Gambia"],
            ["isoCode" => "GH", "name" => "Ghana"],
            ["isoCode" => "GP", "name" => "Guadeloupe"],
            ["isoCode" => "GT", "name" => "Guatemala"],
            ["isoCode" => "GN", "name" => "Guinea"],
            ["isoCode" => "GW", "name" => "Guinea-Bissau"],
            ["isoCode" => "DE", "name" => "Germany"],
            ["isoCode" => "GG", "name" => "Guernsey"],
            ["isoCode" => "GI", "name" => "Gibraltar"],
            ["isoCode" => "HN", "name" => "Honduras"],
            ["isoCode" => "HK", "name" => "Hong Kong"],
            ["isoCode" => "GD", "name" => "Grenada"],
            ["isoCode" => "GL", "name" => "Greenland"],
            ["isoCode" => "GR", "name" => "Greece"],
            ["isoCode" => "GE", "name" => "Georgia"],
            ["isoCode" => "GU", "name" => "Guam"],
            ["isoCode" => "DK", "name" => "Denmark"],
            ["isoCode" => "JE", "name" => "Jersey"],
            ["isoCode" => "DJ", "name" => "Djibouti"],
            ["isoCode" => "DM", "name" => "Dominica"],
            ["isoCode" => "DO", "name" => "Dominican Republic"],
            ["isoCode" => "EG", "name" => "Egypt"],
            ["isoCode" => "ZM", "name" => "Zambia"],
            ["isoCode" => "EH", "name" => "Western Sahara"],
            ["isoCode" => "ZW", "name" => "Zimbabwe"],
            ["isoCode" => "IL", "name" => "Israel"],
            ["isoCode" => "IN", "name" => "India"],
            ["isoCode" => "ID", "name" => "Indonesia"],
            ["isoCode" => "JO", "name" => "Jordan"],
            ["isoCode" => "IQ", "name" => "Iraq"],
            ["isoCode" => "IR", "name" => "Iran"],
            ["isoCode" => "IE", "name" => "Ireland"],
            ["isoCode" => "IS", "name" => "Iceland"],
            ["isoCode" => "ES", "name" => "Spain"],
            ["isoCode" => "IT", "name" => "Italy"],
            ["isoCode" => "YE", "name" => "Yemen"],
            ["isoCode" => "CV", "name" => "Cape Verde"],
            ["isoCode" => "KZ", "name" => "Kazakhstan"],
            ["isoCode" => "KH", "name" => "Cambodia"],
            ["isoCode" => "CM", "name" => "Cameroon"],
            ["isoCode" => "CA", "name" => "Canada"],
            ["isoCode" => "QA", "name" => "Qatar"],
            ["isoCode" => "KE", "name" => "Kenya"],
            ["isoCode" => "CY", "name" => "Cyprus"],
            ["isoCode" => "KG", "name" => "Kyrgyzstan"],
            ["isoCode" => "KI", "name" => "Kiribati"],
            ["isoCode" => "CN", "name" => "China"],
            ["isoCode" => "CC", "name" => "Cocos (Keeling) Islands"],
            ["isoCode" => "CO", "name" => "Colombia"],
            ["isoCode" => "KM", "name" => "Comoros"],
            ["isoCode" => "CG", "name" => "Congo"],
            ["isoCode" => "CD", "name" => "Congo, Democratic Republic of"],
            ["isoCode" => "KP", "name" => "Korea, Democratic People's republic of"],
            ["isoCode" => "KR", "name" => "Korea"],
            ["isoCode" => "CR", "name" => "Costa Rica"],
            ["isoCode" => "CI", "name" => "Cote d'Ivoire"],
            ["isoCode" => "CU", "name" => "Cuba"],
            ["isoCode" => "KW", "name" => "Kuwait"],
            ["isoCode" => "CW", "name" => "Curasao"],
            ["isoCode" => "LA", "name" => "Lao"],
            ["isoCode" => "LV", "name" => "Latvia"],
            ["isoCode" => "LS", "name" => "Lesotho"],
            ["isoCode" => "LB", "name" => "Lebanon"],
            ["isoCode" => "LY", "name" => "Libyan"],
            ["isoCode" => "LR", "name" => "Liberia"],
            ["isoCode" => "LI", "name" => "Liechtenstein"],
            ["isoCode" => "LT", "name" => "Lithuania"],
            ["isoCode" => "LU", "name" => "Luxembourg"],
            ["isoCode" => "MU", "name" => "Mauritius"],
            ["isoCode" => "MR", "name" => "Mauritania"],
            ["isoCode" => "MG", "name" => "Madagascar"],
            ["isoCode" => "YT", "name" => "Mayotte"],
            ["isoCode" => "MO", "name" => "Macao"],
            ["isoCode" => "MW", "name" => "Malawi"],
            ["isoCode" => "MY", "name" => "Malaysia"],
            ["isoCode" => "ML", "name" => "Mali"],
            ["isoCode" => "UM", "name" => "United States Minor Outlying Islands"],
            ["isoCode" => "MV", "name" => "Maldives"],
            ["isoCode" => "MT", "name" => "Malta"],
            ["isoCode" => "MA", "name" => "Morocco"],
            ["isoCode" => "MQ", "name" => "Martinique"],
            ["isoCode" => "MH", "name" => "Marshall Islands"],
            ["isoCode" => "MX", "name" => "Mexico"],
            ["isoCode" => "FM", "name" => "Micronesia"],
            ["isoCode" => "MZ", "name" => "Mozambique"],
            ["isoCode" => "MD", "name" => "Moldova"],
            ["isoCode" => "MC", "name" => "Monaco"],
            ["isoCode" => "MN", "name" => "Mongolia"],
            ["isoCode" => "MS", "name" => "Montserrat"],
            ["isoCode" => "MM", "name" => "Myanmar"],
            ["isoCode" => "NA", "name" => "Namibia"],
            ["isoCode" => "NR", "name" => "Nauru"],
            ["isoCode" => "NP", "name" => "Nepal"],
            ["isoCode" => "NE", "name" => "Niger"],
            ["isoCode" => "NG", "name" => "Nigeria"],
            ["isoCode" => "NL", "name" => "Netherlands"],
            ["isoCode" => "NI", "name" => "Nicaragua"],
            ["isoCode" => "NU", "name" => "Niue"],
            ["isoCode" => "NZ", "name" => "New Zealand"],
            ["isoCode" => "NC", "name" => "New Caledonia"],
            ["isoCode" => "NO", "name" => "Norway"],
            ["isoCode" => "AE", "name" => "United Arab Emirates"],
            ["isoCode" => "OM", "name" => "Oman"],
            ["isoCode" => "BV", "name" => "Bouvet Island"],
            ["isoCode" => "IM", "name" => "Isle of Man"],
            ["isoCode" => "NF", "name" => "Norfolk Island"],
            ["isoCode" => "CX", "name" => "Christmas Island"],
            ["isoCode" => "HM", "name" => "Heard Island and McDonald Islands"],
            ["isoCode" => "KY", "name" => "Cayman Islands"],
            ["isoCode" => "CK", "name" => "Cook Islands"],
            ["isoCode" => "TC", "name" => "Turks and Caicos Islands"],
            ["isoCode" => "PK", "name" => "Pakistan"],
            ["isoCode" => "PW", "name" => "Palau"],
            ["isoCode" => "PS", "name" => "Palestinian Territory"],
            ["isoCode" => "PA", "name" => "Panama"],
            ["isoCode" => "VA", "name" => "Holy See"],
            ["isoCode" => "PG", "name" => "Papua New Guinea"],
            ["isoCode" => "PY", "name" => "Paraguay"],
            ["isoCode" => "PE", "name" => "Peru"],
            ["isoCode" => "PN", "name" => "Pitcairn"],
            ["isoCode" => "PL", "name" => "Poland"],
            ["isoCode" => "PT", "name" => "Portugal"],
            ["isoCode" => "PR", "name" => "Puerto Rico"],
            ["isoCode" => "MK", "name" => "Macedonia"],
            ["isoCode" => "RE", "name" => "Reunion"],
            ["isoCode" => "RU", "name" => "Russian Federation"],
            ["isoCode" => "RW", "name" => "Rwanda"],
            ["isoCode" => "RO", "name" => "Romania"],
            ["isoCode" => "WS", "name" => "Samoa"],
            ["isoCode" => "SM", "name" => "San Marino"],
            ["isoCode" => "ST", "name" => "Sao Tome and Principe"],
            ["isoCode" => "SA", "name" => "Saudi Arabia"],
            ["isoCode" => "SZ", "name" => "Swaziland"],
            ["isoCode" => "SH", "name" => "Saint Helena, Ascension And Tristan da Cunha"],
            ["isoCode" => "MP", "name" => "Northern Mariana Islands"],
            ["isoCode" => "BL", "name" => "Saint Bartholemy"],
            ["isoCode" => "MF", "name" => "Saint Martin (French Part)"],
            ["isoCode" => "SN", "name" => "Senegal"],
            ["isoCode" => "VC", "name" => "Saint Vincent and the Grenadines"],
            ["isoCode" => "LC", "name" => "Saint Lucia"],
            ["isoCode" => "KN", "name" => "Saint Kitts and Nevis"],
            ["isoCode" => "PM", "name" => "Saint Pierre and Miquelon"],
            ["isoCode" => "RS", "name" => "Serbia"],
            ["isoCode" => "SC", "name" => "Seychelles"],
            ["isoCode" => "SG", "name" => "Singapore"],
            ["isoCode" => "SX", "name" => "Sint Maarten"],
            ["isoCode" => "SY", "name" => "Syrian Arab Republic"],
            ["isoCode" => "SK", "name" => "Slovakia"],
            ["isoCode" => "SI", "name" => "Slovenia"],
            ["isoCode" => "GB", "name" => "United Kingdom"],
            ["isoCode" => "US", "name" => "United States"],
            ["isoCode" => "SB", "name" => "Solomon Islands"],
            ["isoCode" => "SO", "name" => "Somalia"],
            ["isoCode" => "SD", "name" => "Sudan"],
            ["isoCode" => "SR", "name" => "Suriname"],
            ["isoCode" => "SL", "name" => "Sierra Leone"],
            ["isoCode" => "TJ", "name" => "Tajikistan"],
            ["isoCode" => "TH", "name" => "Thailand"],
            ["isoCode" => "TW", "name" => "Taiwan"],
            ["isoCode" => "TZ", "name" => "Tanzania"],
            ["isoCode" => "TL", "name" => "Timor-Leste"],
            ["isoCode" => "TG", "name" => "Togo"],
            ["isoCode" => "TK", "name" => "Tokelau"],
            ["isoCode" => "TO", "name" => "Tonga"],
            ["isoCode" => "TT", "name" => "Trinidad and Tobago"],
            ["isoCode" => "TV", "name" => "Tuvalu"],
            ["isoCode" => "TN", "name" => "Tunisia"],
            ["isoCode" => "TM", "name" => "Turkmenistan"],
            ["isoCode" => "TR", "name" => "Turkey"],
            ["isoCode" => "UG", "name" => "Uganda"],
            ["isoCode" => "UZ", "name" => "Uzbekistan"],
            ["isoCode" => "UA", "name" => "Ukraine"],
            ["isoCode" => "WF", "name" => "Wallis and Futuna"],
            ["isoCode" => "UY", "name" => "Uruguay"],
            ["isoCode" => "FO", "name" => "Faroe Islands"],
            ["isoCode" => "FJ", "name" => "Fiji"],
            ["isoCode" => "PH", "name" => "Philippines"],
            ["isoCode" => "FI", "name" => "Finland"],
            ["isoCode" => "FK", "name" => "Falkland Islands (Malvinas)"],
            ["isoCode" => "FR", "name" => "France"],
            ["isoCode" => "GF", "name" => "French Guiana"],
            ["isoCode" => "PF", "name" => "French Polynesia"],
            ["isoCode" => "TF", "name" => "French Southern Territories"],
            ["isoCode" => "HR", "name" => "Croatia"],
            ["isoCode" => "CF", "name" => "Central African Republic"],
            ["isoCode" => "TD", "name" => "Chad"],
            ["isoCode" => "ME", "name" => "Montenegro"],
            ["isoCode" => "CZ", "name" => "Czech Republic"],
            ["isoCode" => "CL", "name" => "Chile"],
            ["isoCode" => "CH", "name" => "Switzerland"],
            ["isoCode" => "SE", "name" => "Sweden"],
            ["isoCode" => "SJ", "name" => "Svalbard and Jan Mayen"],
            ["isoCode" => "LK", "name" => "Sri Lanka"],
            ["isoCode" => "EC", "name" => "Ecuador"],
            ["isoCode" => "GQ", "name" => "Equatorial Guinea"],
            ["isoCode" => "AX", "name" => "Aland Islands"],
            ["isoCode" => "SV", "name" => "El Salvador"],
            ["isoCode" => "ER", "name" => "Eritrea"],
            ["isoCode" => "EE", "name" => "Estonia"],
            ["isoCode" => "ET", "name" => "Ethiopia"],
            ["isoCode" => "ZA", "name" => "South Africa"],
            ["isoCode" => "GS", "name" => "South Georgia and the South Sandwich Islands"],
            ["isoCode" => "OS", "name" => "South Ossetia"],
            ["isoCode" => "SS", "name" => "South Sudan"],
            ["isoCode" => "JM", "name" => "Jamaica"],
            ["isoCode" => "JP", "name" => "Japan"],
            ["isoCode" => "AN", "name" => "Netherland Antilles"],
        ];
    }
}
